DECLARE
  PAS_REC    PASSENGER%ROWTYPE;
  PAS_CURSOR SYS_REFCURSOR;
BEGIN
  OPEN PAS_CURSOR FOR
    SELECT ID, FUL_NAME, AGE, 'City' AS CITY FROM PASSENGER;
  FETCH PAS_CURSOR INTO PAS_REC;
EXCEPTION
  WHEN ROWTYPE_MISMATCH THEN
    DBMS_OUTPUT.PUT_LINE('Exception: ROWTYPE_MISMATCH occurred.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Unexpected error');
END;
/