DECLARE
  PAS_ID  NUMBER := &PAS_ID;
  PAS_REC PASSENGER%ROWTYPE;
BEGIN

SELECT * INTO PAS_REC FROM PASSENGER WHERE ID = PAS_ID;
  CASE PAS_REC.AGE
    WHEN 30 THEN
      DBMS_OUTPUT.PUT_LINE('Passenger ID: ' || PAS_REC.ID);
      DBMS_OUTPUT.PUT_LINE('Passenger Full FUL_NAME: ' || PAS_REC.FUL_NAME);
      DBMS_OUTPUT.PUT_LINE('Passenger AGE: ' || PAS_REC.AGE);
    WHEN 25 THEN
      DBMS_OUTPUT.PUT_LINE('Passenger ID: ' || PAS_REC.ID);
      DBMS_OUTPUT.PUT_LINE('Passenger Full FUL_NAME: ' || PAS_REC.FUL_NAME);
      DBMS_OUTPUT.PUT_LINE('Passenger AGE: ' || PAS_REC.AGE);
    WHEN 35 THEN
      DBMS_OUTPUT.PUT_LINE('Passenger ID: ' || PAS_REC.ID);
      DBMS_OUTPUT.PUT_LINE('Passenger Full FUL_NAME: ' || PAS_REC.FUL_NAME);
      DBMS_OUTPUT.PUT_LINE('Passenger AGE: ' || PAS_REC.AGE);
  END CASE;
EXCEPTION
  WHEN CASE_NOT_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('CASE for Passenger with ID ' || PAS_ID || ' not found.');
  WHEN no_data_found THEN
  DBMS_OUTPUT.PUT_LINE('invali ID ');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Unexpected error: '|| SQLERRM);
END;
/