DECLARE
PAS_ID NUMBER := &PAS_ID;
CURRENT_YEAR NUMBER := &CURRENT_YEAR;
BIRTH_YEAR NUMBER;
AGE PASSENGER.AGE%TYPE;
TOO_LOW EXCEPTION;
PRAGMA EXCEPTION_INIT(TOO_LOW, -20200);

BEGIN
select age into age from PASSENGER WHERE id =PAS_ID;
BIRTH_YEAR := CURRENT_YEAR - AGE;

IF age > CURRENT_YEAR THEN
      RAISE TOO_LOW;
      END IF;
DBMS_OUTPUT.PUT_LINE('You Was Born in  ' || BIRTH_YEAR);

EXCEPTION
WHEN TOO_LOW THEN
DBMS_OUTPUT.PUT_LINE('Invalid: Current year must be higher than Passenger age:' || SQLERRM);
END;
/