DECLARE
  WORKER_NAME WORKERS%ROWTYPE;
  WORKER      SYS_REFCURSOR;
BEGIN
  OPEN WORKER FOR
    SELECT
      ID,
      fNAME,
      AGE,
      'gender' AS GENDER INTO WORKER_NAME
    FROM
      WORKERS
    WHERE
      ID = 2;
  FETCH WORKER INTO WORKER_NAME;
EXCEPTION
  WHEN ROWTYPE_MISMATCH THEN
    DBMS_OUTPUT.PUT_LINE('Row type mismatch exception occurred');
END;
/